### ISSUE TITLE
Exception: Failed to load Image

### ISSUE THREAD

**Issue by flute** [mchome/flutter_advanced_networkimage#83] opened 2019-03-06 02:49 UTC
Can't catch error while image load failed. 

1. Wrong remote image url without `http` or `https` like `MTU1MTU5MzE1OTc3NSM3NjgjanBn.jpg`

2. Bad image url returns 404 or others like `http://example.com/test.png`

![image](https://user-images.githubusercontent.com/5842406/53852592-84468280-3ffd-11e9-9e92-5b3f56ba58a5.png)

my code as blow：

```dart
return Container(
	width: width,
	height: height,
	child: ClipRRect(
		borderRadius: BorderRadius.circular(borderRadius),
		child: TransitionToImage(
			image: AdvancedNetworkImage(imgUrl,
				loadedCallback: () {
					print('It works!');
				},
				loadFailedCallback: () {
					print('Oh, no!');
				},
				loadingProgress: (double progress) {
					print('Now Loading: $progress');
				},
			),
			fit: BoxFit.cover,
		))),
```

**Comment by mchome** [comment] 2019-03-06 02:55
Are you ticking `All Exceptions` in vscode?

**Comment by flute** [comment] 2019-03-06 06:13
> Are you ticking `All Exceptions` in vscode?

This Exceptions is threwed by flutter_advanced_networkimage plugin. App crashed while run.

**Comment by mchome** [comment] 2019-03-06 06:36
The app will not be crashed, unless your debugger crash your app. Try to remove the breakpoint in your debugger.

**Comment by Smagold** [comment] 2019-03-06 18:56
Was throwing the same exception for me prior to `0.4.13`, `All Exceptions` was unchecked. Production-build app was not crashing, exception fired only during debug.

Does not seem to happen anymore but I'd suggest to keep an eye on this.

**Comment by Smagold** [comment] 2019-03-07 17:49
@mchome fired every time I pushed to a screen with `TransitionToImage` / `AdvancedNetworkImage` present. Very randomly, sometimes instantly after the new screen widget builds.
In other cases after you tap on some button that I assume triggers widget rebuild - then the exception throws.
I noticed that OP uses `TransitionToImage` as I do, which could be the reason for these exceptions being passed to the transition wrapper and not being handled in it.

**Comment by mchome** [comment] 2019-03-08 05:54
@Smagold I can't reproduce this in example app, can your create a minimum project to stably reproduce this issue?

**Comment by mchome** [comment] 2019-03-15 07:31
I think this is a debugger issue, so i close it. Feel free to reopen if i am wrong :)

**Closed by mchome** 2019-03-15 07:31 UTC
Labels: need more details, question

**Comment by enricobenedos** [comment] 2019-05-24 13:52
Good morning guys,
I have the same issue at the moment. For some reason today I've changed the image url server endpoint and now the component crash the application because it try to load the images from an old url.

```
I/flutter (31417): ══╡ EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE ╞════════════════════════════════════════════════════
I/flutter (31417): The following _Exception was thrown resolving an image codec:
I/flutter (31417): Exception: Failed to load http://myOldUrl/image.jpg
```

This is a code snippet that I'm using at the moment
```
Image(
             image: AdvancedNetworkImage(
                     imgUrl,
                     useDiskCache: true,
                     cacheRule: CacheRule(maxAge: const Duration(days: 7)),
 ),
fit: BoxFit.cover,),
```

`imgUrl` at the moment is the new endpoint. For any reason the library continue to load the old one. I've tried to do a `DiskCache().clear();` but the problem persist.
